; FINDS THE SUM OF THE INTEGERS IN THE LIST
; R0 IS USED TO TERMINATE PROCESSING
; R1 GETS THE ADDRESS OF THE LIST
; R2 IS THE ACCUMULATOR (SUM) INITALLY 0
; R3 IS USED TO GET THE ADDRESS OF THE NEXT BYTE
; R4 GETS THE VALUE
	LOAD R0, -1
	LOAD R2, 0
	LOAD R3, 1
	LOAD R1, LIST
BACK:	LOAD R4, [R1]
	JMPEQ R4=R0, END
	ADDI R2, R2, R4
	ADDI R1, R1, R3
	JMP BACK
END:	STORE R2, [$FF]
	HALT
LIST:	DB 10, 8, 9, 3, 5, 4, 1, 2, 7, 6, -1